### PR TITLE
Fix for native get() recursion

### LINKED ISSUE #2: Infinite recursion when calling native get()
If trying to call `navigator.credentials.get()` for a "public-key" credential the `get()` call [here](https://github.com/digitalbazaar/credential-handler-polyfill/blob/master/CredentialsContainer.js#L37) will infinitely call itself.

The cause of the problem seems to be that [_nativeCredentialsContainer is saved](https://github.com/digitalbazaar/credential-handler-polyfill/blob/master/CredentialsContainer.js#L18) after the [polyfill has been installed](https://github.com/digitalbazaar/credential-handler-polyfill/blob/master/index.js#L67-L72) so that when the code falls through to calling `_nativeCredentialsContainer.get()` it is actually calling the polyfill instead of the native `CredentialsContainer`.

### PR DESCRIPTION
**Pull request by apowers313**
fixes #2

### CODE REVIEW

File: CredentialsContainer.js [hunk 1]
```diff
@@ -15,7 +15,14 @@ const CREDENTIAL_STORE_TIMEOUT = 0;
 
 export class CredentialsContainer {
   constructor(injector) {
-    this._nativeCredentialsContainer = navigator.credentials;
+    if (typeof navigator.credentials === "object") {
```
Comment (davidlehn) [inline CredentialsContainer.js]: Not a big deal but could probably use `'credentials' in navigator` vs a `typeof` check?

Comment (apowers313) [reply CredentialsContainer.js]: I thought of just checking it as truthy (`if(navigator.credentials)`), but if someone did something stupid like set `navigator.credentials` to a string, it wouldn't fail gracefully. Although, now  that I'm saying that, the code further down would choke on that situation anyway.

I guess it doesn't hurt anything to use the `in` operator.

Comment (dlongley) [reply CredentialsContainer.js]: Note on our coding style -- we use single quotes unless there's some very good reason to use double quotes:

`"object"` => `'object'`

File: CredentialsContainer.js [hunk 2]
```diff
@@ -15,7 +15,14 @@ const CREDENTIAL_STORE_TIMEOUT = 0;
...
+      this._nativeCredentialsContainer = {};
+      this._nativeCredentialsContainer.get = navigator.credentials.get.bind(navigator.credentials);
+      this._nativeCredentialsContainer.store = navigator.credentials.store.bind(navigator.credentials);
+      this._nativeCredentialsContainer.create = navigator.credentials.create.bind(navigator.credentials);
+      this._nativeCredentialsContainer.preventSilentAccess = navigator.credentials.preventSilentAccess.bind(navigator.credentials);
```
Comment (dlongley) [inline CredentialsContainer.js]: Maybe we just use a loop to bind all functions that appear on the object. Thoughts?

**Review by dlongley — CHANGES_REQUESTED** [review]

File: CredentialsContainer.js (hunk 2 above)
Comment (apowers313) [reply CredentialsContainer.js]: Something like:

``` js
Object.keys(navigator.credentials).forEach((key) => {
  if(typeof navigator.credentials[key] === 'function')
    this._nativeCredentialsContainer[key] = navigator.credentials[key].bind(navigator.credentials)];
});
```

Same number of lines of code, but more obfuscated... Also doesn't help unless you somehow attach them to `CredentialsContainer` too.

Comment (davidlehn) [reply CredentialsContainer.js]: I thought about suggesting that too.  Seems for just a few items it's easier to leave it simple like this.

Comment (davidlehn) [reply CredentialsContainer.js]: `Object.keys` wouldn't work.  Would need a `for(const key in navigator.credentials)` sort of construct I think.

Comment (davidlehn) [reply CredentialsContainer.js]: Another option:
```js
['get', 'store', 'create', 'preventSilentAccess'].forEach(key =>
  this._nativeCredentialsContainer[key] = navigator.credentials[key].bind(navigator.credentials)
);
```

Comment (apowers313) [reply CredentialsContainer.js]: I just realized that we need to use a dynamic loop since various implementations (e.g. Firefox) may not have all the same methods implemented. That loop should assign existing methods to the `CredentialsContainer` instance, but catch `get` and `store`. Also, this would obviate the current `CredentialsContainer#create` and `CredentialsContainer#preventSilentAccess` methods.

I'll update my PR accordingly tonight.

**Comment by apowers313** [comment]
Updated PR theory of operation:
1. Note that `navigator.credentials` is readonly, so it's impossible to replace the entire object if it already exists.
2. Current code in [index.js](https://github.com/digitalbazaar/credential-handler-polyfill/blob/master/index.js#L67-L74) will only set `get` and `store` if `navigator.credentials` already exists. If other native methods exist, they won't be overwritten.
3. If `navigator.credentials` doesn't exist the whole `CredentialsContainer` object will be used as the polyfill, which now contains only the `get` and `store` methods. Attempting to call `create` or `preventSilentAccess` will fail as they would have before the polyfill was defined.
4. The new `_nativeCredentialsContainer` object accounts for all contingencies: if `navigator.credentials` is undefined, then both `get` and `store` will be undefined. If either `navigator.credentials.get` or `navigator.credentials.store` is undefined, they will be undefined on `_nativeCredentialsContainer` respectively.
5. The calling of the native functions is based on which of the functions has been defined, rather than whether the whole object exists.

**Review by dlongley — APPROVED** [review]
LGTM.

**Comment by dlongley** [comment]
Works in manual testing (which we need to better automate at some point) ... released in v0.1.7.

Thanks @apowers313!
